"""updated note schema

Revision ID: 18e3f7fcfc17
Revises: 9a82b2b3d367
Create Date: 2026-02-18 19:40:01.412275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e3f7fcfc17'
down_revision: Union[str, None] = '9a82b2b3d367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('note_client_id_key'), 'note', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('note_client_id_key'), 'note', ['client_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
