"""updated note created_by required

Revision ID: 6ec1cf561ae4
Revises: 18e3f7fcfc17
Create Date: 2026-02-19 01:17:13.235500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec1cf561ae4'
down_revision: Union[str, None] = '18e3f7fcfc17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
