"""Remove completed_by foreign key, write name as string instead

Revision ID: 97616699fad6
Revises: 7ef4b70dddb6
Create Date: 2026-02-20 14:33:36.282825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97616699fad6'
down_revision: Union[str, None] = '7ef4b70dddb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('note_completed_by_fkey'), 'note', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('note_completed_by_fkey'), 'note', 'user', ['completed_by'], ['id'])
    # ### end Alembic commands ###
